name: Main Workflow

on:
  push:
    branches:
      - main  # Or whichever branch you want to trigger the workflow

jobs:
  build-and-push-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Frontend Docker Image
        run: docker build -t bruno74t/frontend-image:latest frontend

      - name: Log into Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD_SYMBOLS_ALLOWED }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push Frontend Docker Image
        run: docker push bruno74t/frontend-image:latest

  build-and-push-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Backend Docker Image
        run: docker build -t bruno74t/backend-image:latest backend

      - name: Log into Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD_SYMBOLS_ALLOWED }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push Backend Docker Image
        run: docker push bruno74t/backend-image:latest

